CREATE DATABASE IF NOT EXISTS web_backend_lab;
USE web_backend_lab;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  userId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_posts_user
    FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE
);

-- CRUD examples
SELECT * FROM users;
INSERT INTO users (name, email) VALUES ('Гліб Сухоручкін', 'hlib@example.com');
UPDATE users SET name = 'Гліб Сухоручкін IA-34' WHERE id = 1;
DELETE FROM users WHERE id = 9999;
